export default [
    {code: 'NA', title: 'National'},
    {code: 'AN', title: 'Andaman and Nicobar Islands'},
    {code: 'AP', title: 'Andhra Pradesh'},
    {code: 'AR', title: 'Arunachal Pradesh'},
    {code: 'AS', title: 'Assam'},
    {code: 'BR', title: 'Bihar'},
    {code: 'CG', title: 'Chandigarh'},
    {code: 'CH', title: 'Chhattisgarh'},
    {code: 'DH', title: 'Dadra and Nagar Haveli'},
    {code: 'DD', title: 'Daman and Diu'},
    {code: 'DL', title: 'Delhi'},
    {code: 'GA', title: 'Goa'},
    {code: 'GJ', title: 'Gujarat'},
    {code: 'HR', title: 'Haryana'},
    {code: 'HP', title: 'Himachal Pradesh'},
    {code: 'JK', title: 'Jammu and Kashmir'},
    {code: 'JH', title: 'Jharkhand'},
    {code: 'KA', title: 'Karnataka'},
    {code: 'KL', title: 'Kerala'},
    {code: 'LD', title: 'Lakshadweep'},
    {code: 'MP', title: 'Madhya Pradesh'},
    {code: 'MH', title: 'Maharashtra'},
    {code: 'MN', title: 'Manipur'},
    {code: 'ML', title: 'Meghalaya'},
    {code: 'MZ', title: 'Mizoram'},
    {code: 'NL', title: 'Nagaland'},
    {code: 'OR', title: 'Odisha'},
    {code: 'PY', title: 'Puducherry'},
    {code: 'PB', title: 'Punjab'},
    {code: 'RJ', title: 'Rajasthan'},
    {code: 'SK', title: 'Sikkim'},
    {code: 'TN', title: 'Tamil Nadu'},
    {code: 'TS', title: 'Telangana'},
    {code: 'TR', title: 'Tripura'},
    {code: 'UK', title: 'Uttarakhand'},
    {code: 'UP', title: 'Uttar Pradesh'},
    {code: 'WB', title: 'West Bengal'}
  ];
